# Generated by Django 2.0.2 on 2018-03-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_username', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'twitter_blacklist',
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'followers',
            },
        ),
        migrations.CreateModel(
            name='TargetTwitterAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('twitter_url', models.URLField(null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'target_twitter_accounts',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'twitter_users',
            },
        ),
        migrations.AddField(
            model_name='followers',
            name='user_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='twitterbot.TwitterUser'),
        ),
        migrations.AddField(
            model_name='followers',
            name='user_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='twitterbot.TwitterUser'),
        ),
    ]
