# Generated by Django 2.0.2 on 2018-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetTwitterAccounts',
        ),
        migrations.CreateModel(
            name='TargetTwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=50)),
                ('followers_count', models.PositiveIntegerField(null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'target_twitter_accounts',
            },
        ),
        migrations.CreateModel(
            name='TwitterFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=50)),
                ('followers_count', models.PositiveIntegerField(null=True)),
                ('user_type', models.IntegerField(choices=[(1, 'Friend'), (2, 'Follower')], null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'twitter_followers',
            },
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user_id1',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user_id2',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='twitter_username',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='user_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
