# Generated by Django 2.0.2 on 2018-04-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetTwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=50)),
                ('followers_count', models.PositiveIntegerField(null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'target_twitter_accounts',
            },
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user_id1',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user_id2',
        ),
        migrations.DeleteModel(
            name='TargetTwitterAccounts',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Friend'), (2, 'Follower')], null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
