# Generated by Django 2.0.2 on 2018-04-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0002_auto_20180419_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targettwitteraccount',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='targettwitteraccount',
            name='location_country_code',
        ),
        migrations.RemoveField(
            model_name='targettwitteraccount',
            name='location_region',
        ),
        migrations.RemoveField(
            model_name='targettwitteraccount',
            name='organization',
        ),
        migrations.AddField(
            model_name='targettwitteraccount',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='targettwitteraccount',
            name='is_follower',
            field=models.BooleanField(default=False),
        ),
    ]
