# Generated by Django 2.0.2 on 2018-05-02 10:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0004_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUserWithTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=50, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'twitter_users_with_tags',
            },
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
