# Generated by Django 2.0.2 on 2018-06-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0006_whitelisttwitteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=50, unique=True)),
                ('consumer_key', models.CharField(blank=True, max_length=50, null=True)),
                ('consumer_secret', models.CharField(blank=True, max_length=50, null=True)),
                ('access_token', models.CharField(blank=True, max_length=50, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='blacklist',
            name='account_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterbot.AccountOwner'),
        ),
        migrations.AddField(
            model_name='targettwitteraccount',
            name='account_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterbot.AccountOwner'),
        ),
        migrations.AddField(
            model_name='twitterfollower',
            name='account_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterbot.AccountOwner'),
        ),
        migrations.AddField(
            model_name='verifieduserwithtag',
            name='account_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterbot.AccountOwner'),
        ),
        migrations.AddField(
            model_name='whitelisttwitteruser',
            name='account_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterbot.AccountOwner'),
        ),
    ]
