# Generated by Django 2.0.2 on 2018-06-25 07:57

from django.db import migrations


def populate_tables_with_twitter_account_owners(apps, schema_editor):
    AccountOwner = apps.get_model('twitterbot.AccountOwner')
    TwitterFollower = apps.get_model('twitterbot.TwitterFollower')
    TargetTwitterAccount = apps.get_model('twitterbot.TargetTwitterAccount')
    BlackList = apps.get_model('twitterbot.BlackList')
    VerifiedUserWithTag = apps.get_model('twitterbot.VerifiedUserWithTag')

    AccountOwner.objects.create(screen_name='goformoonshot')
    AccountOwner.objects.create(screen_name='a_soldatenko')

    moonshot = AccountOwner.objects.get(screen_name='goformoonshot')

    TwitterFollower.objects.all().update(account_owner=moonshot)
    TargetTwitterAccount.objects.all().update(account_owner=moonshot)
    BlackList.objects.all().update(account_owner=moonshot)
    VerifiedUserWithTag.objects.all().update(account_owner=moonshot)


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0007_auto_20180625_0757'),
    ]

    operations = [
        migrations.RunPython(populate_tables_with_twitter_account_owners)
    ]
