# Generated by Django 2.0.2 on 2020-03-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0011_whitelisttwitteruser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTasksTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('execution_time', models.DateTimeField()),
                ('executed', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'run_tasks',
            },
        ),
    ]
