# Generated by Django 2.0.2 on 2020-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0012_runtaskstimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountowner',
            name='csv_statistic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountowner',
            name='follow_all_followers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountowner',
            name='followers_limit',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='accountowner',
            name='retweet_func',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountowner',
            name='target_account_followers_count',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
