# Generated by Django 2.0.2 on 2020-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0013_auto_20200408_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterfollower',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
