# Generated by Django 2.0.2 on 2020-09-08 20:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0014_twitterfollower_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountowner',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='words searched in description of target accounts', null=True, size=None),
        ),
    ]
